commands:
   heads:
      label: 'heads'
      aliases:
      - 'head'
      description: 'Get cool heads'
      sub-commands:
         reload: 'reload'
         add: 'add'
         hand: 'hand'
         random: 'random'
         remove: 'remove'
         rename: 'rename'
         get: 'get'
         give: 'give'
         search: 'search'
         cost: 'cost'
         category-cost: 'categorycost'
         id: 'id'
         help: 'help'
         # open menu is when no arguments are supplied
economy:
   enabled: false
   # Use 0 for no cost
   default-head-cost: 0
breaking-head-names:
   enabled: true
   attempt-hook-blockstore: true
   similar-heads-in-cache: true
   default-name: 'Decoration Head'
hide-no-perm-categories: true
check-for-updates: true