commands:
   heads:
      label: 'heads'
      aliases:
      - 'head'
      description: 'Get cool heads'
      sub-commands:
         reload: 'reload'
         add: 'add'
         hand: 'hand'
         random: 'random'
         remove: 'remove'
         rename: 'rename'
         get: 'get'
         give: 'give'
         search: 'search'
         cost: 'cost'
         category-cost: 'categorycost'
         item-eco: 'itemeco'
         id: 'id'
         help: 'help'
         # open menu is when no arguments are supplied
economy:
   enabled: false
   default-head-cost: 0
   vault-eco:
      enabled: true
   item-eco:
      enabled: false
      item:
         type: skull_item
         data: 3
         name: '&6Player Head Token'
         lore:
         - '&8Use in /heads!'
   player-points-eco:
      enabled: false
breaking-head-names:
   enabled: true
   attempt-hook-blockstore: true
   similar-heads-in-cache: true
   default-name: 'Decoration Head'
hide-no-perm-categories: true
check-for-updates: true