main: net.sothatsit.heads.Heads
author: sothatsit
name: Heads
version: 1.11.0
soft-depend: [Vault, BlockStore]
permissions:
   heads.reload:
      description: 'Reload the legacy files'
      default: op
   heads.menu:
      description: 'Open the head menu'
      default: op
   heads.get:
      description: 'Use the /heads get <name> command'
      default: op
   heads.search:
      description: 'Use the /heads search <search query> command'
      default: op
   heads.add:
      description: 'Add heads to the legacy'
      default: op
   heads.hand:
      description: 'Add heads from your hand into the legacy'
      default: op
   heads.random:
      description: 'Get a random head from the legacy'
      default: op
   heads.remove:
      description: 'Remove heads from the legacy'
      default: op
   heads.rename:
      description: 'Rename heads in the legacy'
      default: op
   heads.id:
      description: 'Get a heads id'
      default: op
   heads.give:
      description: 'Give players heads'
      default: op
   heads.cost:
      description: 'Set heads costs'
      default: op
   heads.category-cost:
      description: 'Set heads costs by category'
      default: op
   heads.bypasscost:
      description: 'Bypass paying for heads'
      default: op
   heads.category.*:
      description: 'Permission for all categories'
      default: true