main: net.sothatsit.heads.Heads
author: sothatsit
name: Heads
version: 1.14.3
soft-depend: [Vault, PlayerPoints, BlockStore]
permissions:
   heads.reload:
      description: 'Reload the config files'
      default: op
   heads.menu:
      description: 'Open the head menu'
      default: op
   heads.get:
      description: 'Use the /heads get <name> command'
      default: op
   heads.search:
      description: 'Use the /heads search <search query> command'
      default: op
   heads.add:
      description: 'Add heads to the cache'
      default: op
   heads.hand:
      description: 'Add heads from your hand into the cache'
      default: op
   heads.random:
      description: 'Get a random head from the cache'
      default: op
   heads.remove:
      description: 'Remove heads from the cache'
      default: op
   heads.rename:
      description: 'Rename heads in the cache'
      default: op
   heads.id:
      description: 'Get a heads id'
      default: op
   heads.give:
      description: 'Give players heads'
      default: op
   heads.cost:
      description: 'Set heads costs'
      default: op
   heads.category-cost:
      description: 'Set heads costs by category'
      default: op
   heads.bypasscost:
      description: 'Bypass paying for heads'
      default: op
   heads.category.*:
      description: 'Permission for all categories'
      default: true
   heads.item-eco:
      description: 'Permission to set, get and give the economy item'
      default: op